export const SET_LOGIN_STATE = 'SET_LOGIN_STATE';
export const SET_LOGOUT_STATE = 'SET_LOGOUT_STATE';
export const SET_SIGNUP_STATE = 'SET_SIGNUP_STATE';
export const CHANGE_NICKNAME = 'CHANGE_NICKNAME';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PROFILE_IMG = 'CHANGE_PROFILE_IMG';
export const PRODUCTDETAIL_INFO = 'PRODUCTDETAIL_INFO';
export const PRODUCTDETAIL_BOOKMARK = 'PRODUCTDETAIL_BOOKMARK';
